version: 2.1

jobs:
  build-images:
    resource_class: large
    docker:
      - image: cimg/python:3.7
    environment:
      TAG: '0.0.1'
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
          docker_layer_caching: false  # for now
      - run:
          name: Install dependencies
          command: |
            # ideally, use Poetry or Pipenv for Python dependency management
            pip install -r requirements.txt
      - run:
          name: Build images
          command: |
            python build_images.py complete slim nginx
      - run:
          name: Check images
          command: |
            docker image ls

workflows:
  main:
    jobs:
      - build-images
