version: 2.1

jobs:
  build-images:
    resource_class: large
    machine:
      image: ubuntu-2004:202111-02
    environment:
      TAG: '0.0.1'
    steps:
      - checkout
      - run:
          name: Diagnostics
          command: |
            which aws
            aws --version || true
      - run:
          name: Install dependencies
          command: |
            # ideally, use Poetry or Pipenv for Python dependency management
            pip3 install -r requirements.txt
      - run:
          name: Build images
          command: |
            python3 build_images.py complete slim nginx
      - run:
          name: Check images
          command: |
            docker image ls

workflows:
  main:
    jobs:
      - build-images
